### ISSUE TITLE
Example is wrong?

### ISSUE THREAD

**Issue by gattidaniel** [htwyford/chartist-plugin-targetline#1]
Hi,
I think that the example must have Chartist.plugins. before ctTargetLine

```
var chart = new Chartist.Line('.ct-chart', {
  labels: [1, 2, 3, 4, 5, 6, 7],
  series: [
    [1, 5, 3, 4, 6, 2, 3],
    [2, 4, 2, 5, 4, 3, 6]
  ]
}, {
  plugins: [
     Chartist.plugins.ctTargetLine({
      value: 1000
    })
  ]
});
```

Because if not, it is not defined

**Comment by htwyford** [comment]
Fixed in https://github.com/htwyford/chartist-plugin-targetline/commit/6526ba5e0999ebf829410a80de184f5748bdaa1a. Thanks!
